/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.CiudadC;
import Controller.ContinenteC;
import Controller.EstadoC;
import Controller.PaisC;
import Model.Entity.Ciudad;
import Model.Entity.Continente;
import Model.Entity.Estado;
import Model.Entity.Pais;
import java.util.ArrayList;
import java.util.List;


/**
 *
 * @author juan
 */
public class Eliminar extends javax.swing.JFrame {

    /**
     * Creates new form Eliminar
     */
    public Eliminar() {

        initComponents();
                String valorSeleccionado= (String)ComboBoxTabla.getSelectedItem();
        System.out.println(valorSeleccionado);
    }
     private void ConsultaContinente() {

        try {
            ContinenteC controlador = new ContinenteC();
            ArrayList<Continente> listaDeProductos = controlador.ConsultarRegistro();


            for (Continente continente : listaDeProductos) {
                Object[] fila = new Object[2]; // Asumo que tu tabla tiene 6 columnas

                //fila[0] = producto.getId(); // Reemplaza con el método adecuado para obtener el ID
                fila[0] = continente.getCodigo_postal();
                fila[1] = continente.getDescripcion();

            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ConsultaPais() {

        try {
            PaisC controlador = new PaisC();
            ArrayList<Pais> listaDeProductos = controlador.ConsultarRegistro();



            for (Pais pais : listaDeProductos) {
                Object[] fila = new Object[3];

                fila[0] = pais.getCodigo_postal();
                fila[1] = pais.getDescripcion();
                fila[2] = pais.getId_continente();


            }

        } catch (Exception e) {
            e.printStackTrace();
        }

    }

    private void ConsultaEstado() {

        try {
            EstadoC controlador = new EstadoC();
            ArrayList<Estado> listaDeProductos = controlador.ConsultarRegistro();



            for (Estado estado : listaDeProductos) {
                Object[] fila = new Object[3]; // Asumo que tu tabla tiene 6 columnas

                //fila[0] = producto.getId(); // Reemplaza con el método adecuado para obtener el ID
                fila[0] = estado.getCodigo_postal();
                fila[1] = estado.getDescripcion();
                fila[2] = estado.getId_pais();


            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void ConsultaCiudad() {

        try {
            CiudadC controlador = new CiudadC();
            ArrayList<Ciudad> listaDeProductos = controlador.ConsultarRegistro();

            for (Ciudad ciudad : listaDeProductos) {
                Object[] fila = new Object[3]; // Asumo que tu tabla tiene 6 columnas

                //fila[0] = producto.getId(); // Reemplaza con el método adecuado para obtener el ID
                fila[0] = ciudad.getCodigo_postal();
                fila[1] = ciudad.getDescripcion();
                fila[2] = ciudad.getId_estado();


            }


        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ComboBoxTabla = new javax.swing.JComboBox<>();
        ComboBoxNombre = new javax.swing.JComboBox<>();
        ButtonEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Qué desea Eliminar?");

        ComboBoxTabla.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Continente", "Pais", "Estado", "Ciudad" }));
        ComboBoxTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTablaActionPerformed(evt);
            }
        });

        ComboBoxNombre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxNombreActionPerformed(evt);
            }
        });

        ButtonEliminar.setText("Eliminar");
        ButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(ComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ButtonEliminar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxTabla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 221, Short.MAX_VALUE)
                .addComponent(ButtonEliminar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTablaActionPerformed
        String valorSeleccionado= (String)ComboBoxTabla.getSelectedItem();
        System.out.println(valorSeleccionado);
        
        
         switch (valorSeleccionado) {
            case "Continente":
            case "Pais":
            case "Estado":
            case "Ciudad":
            
         default:
            // No se hace nada
            break;
        }
        
    }//GEN-LAST:event_ComboBoxTablaActionPerformed

    private void ComboBoxNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxNombreActionPerformed

    private void ButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEliminarActionPerformed
       
    }//GEN-LAST:event_ButtonEliminarActionPerformed
    

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eliminar().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEliminar;
    private javax.swing.JComboBox<String> ComboBoxNombre;
    private javax.swing.JComboBox<String> ComboBoxTabla;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
